#!/usr/bin/env php
<?php
	$app_root = rtrim(getenv('OPENSHIFT_REPO_DIR'),'/');
	$www_dir  = $app_root.'/www';
	passthru("cd $app_root && php $app_root/bin/composer update");
	$host = getenv('OPENSHIFT_MYSQL_DB_HOST');
	$port = getenv('OPENSHIFT_MYSQL_DB_PORT');
	$user = getenv('OPENSHIFT_MYSQL_DB_USERNAME');
	$password = getenv('OPENSHIFT_MYSQL_DB_PASSWORD');
	$database	 = getenv('OPENSHIFT_APP_NAME').'_production';
	$cmd = function($cmd) use($app_root) {
		passthru("cd $app_root && php $app_root/vendor/bin/anahita $cmd");
	};
	$init_cmd = "site:init -n --database-prefix=demo --database-dump=$app_root/data/data.sql --database-name=$database --database-user=$user --database-password=$password --database-port=$port --database-host=$host";
	$data_dir = $app_root.'/.openshift';
	$cmd($init_cmd);
	$cmd("package:install connect photos topics html todos groups");
	$cmd("site:configuration --new-secret");
	//install apps
	$cmd("db:migrate:up");		
?>
